"""
The consumer script must be deployed with the same container definition as the web server but different entrypoint.
"""

import time

from src.marketplace.domain.models import Product
from src.marketplace.infrastructure.adapters.db import get_redis_session
from src.marketplace.application.products import update_quantity


key = "payment_completed"
group = "payments"

try:
    with get_redis_session() as session:
        session.xgroup_create(key, group, mkstream=True)
except Exception as e:
    print(e)
    pass

while True:
    try:
        with get_redis_session() as session:
            results = session.xreadgroup(group, key, {key: ">"}, block=0)
            if results:
                for result in results:
                    data: dict = results[0][1][0]
                    updated_product: Product | None = update_quantity(data["product_id"], int(data["quantity"]))
                    if not updated_product:
                        session.xadd("refund_payment", data, "*")  # Topic, Data, ID (* -> autogenerated)
    except Exception as e:
        print(e)

    time.sleep(1)
